### ISSUE TITLE
Clarify, who gets the donations and what will they be used for

### ISSUE THREAD

**Issue by Madis0** [CaffeineMC/caffeine-meta#11]
On https://caffeinemc.net/donate aka https://jellysquid.me/donate, the wording says:

> Feel like thanking me for my open-source projects? Your support helps me spend more time on these projects and gives me the opportunity to do something nice for myself every once in a while.
> 
> On Ko-fi, you can support me by making either a recurring or one-time donation. You won't receive any special rewards or perks from making a donation, other than a token of my appreciation.

By that wording, one may assume that the donations go solely to jellysquid3. 
Which is fine, except... that link is still prominent on Sodium settings screen and [you've announced that you've stopped working on Sodium](https://discord.com/channels/602796788608401408/651120262129123330/976912787332821013). [(via)](https://caffeinemc.net/discord)

So, the questions:

- is it still correct that you are _not_ the primary maintainer of Sodium, or have you returned?
- are donations received and used by you solely, or CaffeineMC as a whole?
- are donations used for CaffeineMC projects, if so - only Sodium or more than that?

You don't have to answer the questions in this issue, I'd prefer if you just edited the donations page text to clarify them.

**Comment by jellysquid3** [comment]
> Which is fine, except... that link is still prominent on Sodium settings screen and [you've announced that you've stopped working on Sodium](https://discord.com/channels/602796788608401408/651120262129123330/976912787332821013). [(via)](https://caffeinemc.net/discord)

Yes, for a while, I stepped away from the project, but a quick look at GitHub would show you that I'm still the primary contributor, accounting for over 90% of the changes:

![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/1363084/35a0000e-1ead-4a9c-9385-1b33e204e1b6)

I'm not sure you are actually confused about this, given it seems impossible to not believe that I am still largely responsible for the development of Sodium, and always have been.

> ... are donations received and used by you solely, or CaffeineMC as a whole?
> ... are donations used for CaffeineMC projects, if so - only Sodium or more than that?

Donations to Sodium are used to fund a small number of expenses the team has (domain names, web servers, software licenses, etc) but they otherwise go to me, which was agreed upon by the rest of the team. The other maintainers of Sodium take a split of the ad revenue, with me having the smallest denominator.

For Lithium, the current maintainer is 2No2Name, and they take 100% of the ad revenue and 100% of the donations, while having exclusivity over the donation links that are shown in the mod.

**Comment by Madis0** [comment]
Got it, so the site's description remains valid.
