### ISSUE TITLE
Restore Curseforge support

### ISSUE THREAD

**Issue by Tenchu98** [CaffeineMC/caffeine-meta#8]
Seeing as next to no platform supports modrinth for searcing mods, I am requesting restoring the curseforge page for the latest versions. Only having modrinth support makes pack development more of a pain.

**Comment by Tenchu98** [comment]
Well if this od stays as modrinth only then I will lose my only reason to run fabric at all.

**Comment by Tenchu98** [comment]
lol I guess the irony is strong with the dev
"More often than not, someone will attempt to do the bare-minimum required to port our mods, take and staple the words "Forge" next to the name we've made for ourselves, and then release it online with no intention to provide support or even reasonably maintain it. This inadvertently leads to our reputation being hurt as the port rots and issues accumulate, and eventually we're faced with an onslaught of users coming to us for help with something we have no affiliation with."

**Comment by jellysquid3** [comment]
You do not understand irony, and venting on our issue tracker over the issue is not helpful nor constructive. We're not going to restore downloads on CurseForge, and more importantly, we are under no obligation to do so. I understand this is inconvenient for people hosting modpacks on CurseForge, but there are workarounds (i.e. uploading the JAR file into the modpack directly.)

**Comment by Tenchu98** [comment]
well venting finally got a response, so it was helpful. Also I probably understand irony better than you do. Either way though your mod is officially dead to me, and I will be encouraging others to abandon it altogether as well.

**Comment by jellysquid3** [comment]
> You just don't do that with a core mod like Sodium.

We should not be required to do _anything_ for the community. In reality, we contribute our time, for free, to a mod that is made under an open source license for people to use with almost no practical restrictions, under the hope that it might be useful for people. We do not gain anything from people using our software, and it is unreasonable for people to dictate that we upload our mods to a certain platform to make it more convenient for others.

This issue is really simple. We do not want people who go to download our mod, people who are usually very young, to be subjected to CurseForge's aggressive advertising or adware-filled launcher. We don't want to support a platform who makes us fight tooth and nail to get obvious malware using our brand taken down. And I don't want to support a platform which makes me wait months to get access restored to my account because none of their employees can respond to an email or support ticket.

There are many issues we've had with CurseForge, but I don't really feel like I need to write a multi-page essay going into detail about it. It should be sufficient to say that we simply don't want to work with them.

You can feel differently about this, and I can certainly understand why you might feel that way, but at the end of the day, you just have no rights to tell us otherwise. If Sodium is such a core mod to the community, then said community will have to either apply pressure on CurseForge to improve their platform, or make it easier to build modpacks which do not rely on CurseForge.

**Comment by Tenchu98** [comment]
Or they will simply abandon sodium and fabric in favor of a more supported set of mods and loader. You can try the high horse, better than though, approach all you want but at the end of the day you have alienated 95% of your user base, and hurt the fabric loaders support. You don't owe anything to the community, and it's your choice at the end of the day. It is also my choice to push for blacklisting your mod in the community, since you are now guilty of the same lack of support you blame the forked mods of doing.

**Comment by TH3N3WN00B** [comment]
Or simply move your modpack to modrinth and ask the comunity to do the same since there are so many issues and so many mod devs that are doing the same instead of making a issue in github?
